### PR TITLE
Add dial support to volume change action

### PR DESCRIPTION
**Pull request by Qalthos**
This also does muting with a press, but change seemed like the most fitting place to put it.

### CODE REVIEW

**Comment by SilentSwordmaiden** [comment]
I really hadn't had the chance to figure out what the dial does, so I didn't touch it yet. Can you give me a quick idea of how to use it? I hesitate to merge something, that I'm not sure how to use :D

I mean, my stream deck does have keys, but no dial?

**Comment by Qalthos** [comment]
So you do have to have a stream deck with dials to use it on hardware, but the fake decks you can make in developer settings are laid out like a Stream Deck +, presumably to help supporting things like this.

You can test it yourself by adding a fake deck and attaching the action to the dial as you would a button. The usual button face is assigned to that section of the touchscreen bar above it, and the dial can be manipulated in the UI by double clicking the dial (as you would a button) or scrolling over the dial (scrolling up emulates clockwise rotation, and down counterclockwise). It seems to work identically to my actual plus, as expected.

**Comment by SilentSwordmaiden** [comment]
Hey, thanks for the help! I could test it now.

It works, but when I start StreamConroller from my terminal, I get 3 messages on the command line every time I do anything with the volume buttons.

```
2024-08-19 20:03:32.146 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_swordmaiden_xivdeck::VolumeChange, state: 0
2024-08-19 20:03:32.146 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_swordmaiden_xivdeck::VolumeChange, state: 0
2024-08-19 20:03:32.146 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_swordmaiden_xivdeck::VolumeChange, state: 0
2024-08-19 20:03:32.151 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_swordmaiden_xivdeck::VolumeChange, state: 0
2024-08-19 20:03:32.151 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_swordmaiden_xivdeck::VolumeChange, state: 0
2024-08-19 20:03:32.151 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_swordmaiden_xivdeck::VolumeChange, state: 0
```

**Comment by Qalthos** [comment]
Okay, it took me a _while_ to figure out, but I have finally reproduced the issue, and it is either a StreamController bug, or it is a problem affecting more than just this implementation.

What the error is saying, as near as I can tell from reading the StreamController source, is that when trying to update the label on the action, it could not find a state associated with the input event it received. I was finally able to reproduce this by doing the only thing I could figure out to have an assigned action have a reference to a nonexistant dial, by assigning the page with the dial action to a deck that had no dials.

Interestingly, not only did the message continue to be emitted when returned to the Plus, it also had the same effect on other actions that had been on other dials on the page like so:

```
2024-08-22 19:38:21.730 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_gapls_AudioControl::DialController, state: 0
2024-08-22 19:38:21.991 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_gapls_AudioControl::DialController, state: 0
2024-08-22 19:38:22.691 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_gapls_AudioControl::DialController, state: 0
2024-08-22 19:38:22.875 | ERROR    | src.backend.PluginManager.ActionBase:set_label:227 - Could not find state, action: com_gapls_AudioControl::DialController, state: 0
```

There _might_ be a way to code defensively around this, but there doesn't seem to be any documentation about it. In any case, a full quit and restart seems to take care of the issue, as long as the page isn't later loaded on a deck with no dials.

**Comment by SilentSwordmaiden** [comment]
Yeah, I noticed it with another audio plugin, too. So it's not your fault^^

**Pull request merged**
